const FETCH_CRIME_LOADING = "FETCH_CRIME_LOADING"
const FETCH_CRIME_SUCCESS = "FETCH_CRIME_SUCCESS"
const FETCH_CRIME_FAILURE = "FETCH_CRIME_FAILURE"

export { FETCH_CRIME_LOADING, FETCH_CRIME_SUCCESS, FETCH_CRIME_FAILURE }