const FETCH_SEARCH_LOADING = "FETCH_SEARCH_LOADING"
const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS"
const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE"

export { FETCH_SEARCH_LOADING, FETCH_SEARCH_SUCCESS, FETCH_SEARCH_FAILURE}