const FETCH_NBHD_LOADING = "FETCH_NBHD_LOADING"
const FETCH_NBHD_SUCCESS = "FETCH_NBHD_SUCCESS"
const FETCH_NBHD_FAILURE = "FETCH_NBHD_FAILURE"

export { FETCH_NBHD_LOADING, FETCH_NBHD_SUCCESS, FETCH_NBHD_FAILURE }